# database configs
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/payments?useTimezone=true&serverTimezone=America/Sao_Paulo"
    username: payments
    password: payments
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: payments
    password: payments
server:
  servlet:
    context-path: /incubator-state-machine

# rabbitmq's data
payments:
  broker:
    exchange: state-machine
    queue:
      email: email
      fraud: fraud
      error: error
    routing-key:
      email: state_machine_routing_key_email
      fraud: state_machine_routing_key_fraud
      error: state_machine_routing_key_error
