package com.statemachine.demo.statemachine.payments;

public enum PaymentState {
    STARTED,
    IN_ANALYSIS,
    SERASA_IN_ANALYSIS,
    SERASA_ANALYSIS_FINISHED,
    CREDIT_CARD_IN_ANALYSIS,
    CREDIT_ANALYSIS_FINISHED,
    JOIN_ALL_ANALYSIS,
    ANALYSIS_FINISHED,
    TRY_TO_PAY,
    REJECTED_BY_FRAUD,
    AUTHORIZED,
    NOT_AUTHORIZED;
}
